/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import main.Game;
import pokemon.AbstractPokemon;
import pokemon.Pokedex;

import javax.swing.*;
import java.awt.*;

/**
 * @author xpcDV
 */
public class SwitchPokemonGUI extends javax.swing.JDialog {

  /**
   * Creates new form SwitchPokemonGUI
   */
  Pokedex pokedex;

  public SwitchPokemonGUI(JFrame parent, Pokedex pokedex) {
    super(parent);
    this.pokedex = pokedex;
    initComponents();

    setLayout(new BorderLayout());

    jPanel1 = new JPanel(new GridLayout(3, 3, 10, 10));
    jPanel1.setPreferredSize(new Dimension(600, 600));

    for (int index = 0; index < this.pokedex.getSize(); index++) {
      AbstractPokemon pokemon = this.pokedex.getPokemon(index);
      JButton newButton = new JButton(pokemon.getName());
      newButton.setIcon(new ImageIcon(pokemon.getImageIcon()));
      newButton.setPreferredSize(new Dimension(200, 200)); // Increase the button size to make them visible
      System.out.println("Pokedex en Switch: " + this.pokedex);
      newButton.addActionListener(e -> {
        newButton.setEnabled(false);
        AbstractPokemon clickedPokemon = this.pokedex.getPokemon(newButton.getText());
        if (clickedPokemon != null && clickedPokemon.getActualHP() > 0) {
          System.out.println("Click: " + clickedPokemon);
          AbstractPokemon actualPokemon = Game.getInstance().getPantallaCombate().getActualUserPokemon();
          // Update actual HP in pokedex
          Game.instance.getPantallaCombate().getUserPokedex().getPokemon(actualPokemon.getName())
                  .setActualHP(actualPokemon.getActualHP());
          // Update the GUI to use the new actual pokemon
          Game.instance.getPantallaCombate().updateUserPokemon(clickedPokemon);
          System.out.println(Game.instance.getPantallaCombate().getActualUserPokemon());
          // close dialog window
        }
        this.dispose();

      });
      jPanel1.add(newButton);
    }
    add(jPanel1, BorderLayout.CENTER); // Add the button panel to the center of the dialog

    setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    setSize(750, 750);
    setLocationRelativeTo(parent);
    setResizable(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jLabel1.setText("EquipoPokemon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
